INSERT INTO UnitIndex (name, abbreviation, dimension) VALUES
--Mass
('grams','g','mass'),
('pounds','lb','mass'),
('ounces','oz','mass'),
('kilograms','kg','mass'),
('milligrams','mg','mass'),
('stone','st','mass'),
--Volume
('milliliters','mL','volume'),
('liters','L','volume'),
('cups','cup','volume'),
('quarts','qt','volume'),
('gallons','gal','volume'),
('pints','pt','volume'),
('gills','gill','volume'),
('fluid ounces','fl oz','volume'),
('tablespoons','tbsp','volume'),
('teaspoons','tsp','volume'),
--Length
('meters','m','length'),
('centimeters','cm','length'),
('feet','ft','length'),
('inches','in','length'),
('yards','yd','length'),
('kilometers','km','length'),
('miles','mi','length'),
--Energy
('Calories','Cal','energy'),
('jewels','J','energy'),
--Time
('seconds','s','time'),
('minutes','min','time'),
('hours','hr','time'),
--Speed
('meters/second','m/s','speed'),
('miles/hour','mph','speed'),
('kilometers/hour','kmph','speed'),
('deleted unit', 'del', 'deleted');
