# Manually triggered Sphinx docs generation

name: Manual Docs Gen

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Documentation media format to target'
        default: 'html'
        required: true

jobs:
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Setup our python version and dependencies
    - name: Checkout
      uses: actions/checkout@v3
    - name: Python setup
      uses: actions/setup-python@v4.0.0
      with:
        # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: '3.10'
    - name: Install requirements_dev.txt
      run: pip install -r requirements_dev.txt
    # Build the docs
    - name: Generate docs
      run: |
          echo "Generating docs for target type ${{ github.event.inputs.type }}"
          python -m sphinx-build -b ${{ github.event.inputs.type }} docs/source/ docs/build/res/
          tar -czf latest-docs.tar.gz docs/build/res/
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: latest-docs
        path: latest-docs.tar.gz
